# @package habitat.dataset
defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: LangMultiObjectNav-v1
split: train
data_path: data/datasets/langmon/hssd-hab/v0.1/{split}/{split}.json.gz
scenes_dir: data/scene_datasets/hssd-hab/scenes
